spring:
  application:
    name: rest-api
  datasource:
    url: jdbc:h2:file:./db.sql
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: guest
    username: guest
